apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app.kubernetes.io/name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webserver
    spec:
      containers:
        - name: webserver
          image: docker.io/professorsam/cityquiz_webserver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: user-name
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: user-password
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: cityquiz
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: filestorage-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: filestorage-secret
                  key: secret-key
            - name: MINIO_ENDPOINT
              value: http://minio:9000
            - name: MINIO_BUCKET
              value: "cityquizimgs"
            #- name: MSSQL_JDBC_URL # -> Overrides MySQL to MS SQL Server
            #  value: "jdbc://..."


