apiVersion: v1
kind: Service
metadata:
  name: http-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: webserver
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
