<style>
    body {
        margin: 0;
        padding: 0;
        font-family: Arial, sans-serif;
    }

    .header {
        background-color: #7AC6C7;
        height: 8vh;
        display: flex;
        align-items: center;
        justify-content: left;
    }

    .header-text {
        color: white;
        font-size: 30px;
        margin-left: 2rem;
    }
</style>
<header>
    <div class="header">
        <div class="header-text">City Quiz</div>
    </div>
</header>