apiVersion: v1
kind: Secret
metadata:
  name: secrets
data:
  db-root-password: {{ .Values.mysql.auth.rootPassword | b64enc }}
  db-user-password: {{ .Values.mysql.auth.password| b64enc }}
  db-user-name: {{ .Values.mysql.auth.username | b64enc }}
  filestorage-access-key: {{ .Values.filestorage.accesskey | b64enc }}
  filestorage-secret-key: {{ .Values.filestorage.secretkey | b64enc }}
  adminpanel-token: {{ .Values.webserver.token | b64enc }}